"""empty message

Revision ID: 1ad52f761676
Revises: 8f38993324e3
Create Date: 2022-07-31 23:34:23.032915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ad52f761676'
down_revision = '8f38993324e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_date_of_birth_key', 'user', type_='unique')
    op.drop_constraint('user_last_name_key', 'user', type_='unique')
    op.drop_constraint('user_name_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_name_key', 'user', ['name'])
    op.create_unique_constraint('user_last_name_key', 'user', ['last_name'])
    op.create_unique_constraint('user_date_of_birth_key', 'user', ['date_of_birth'])
    # ### end Alembic commands ###
