"""empty message

Revision ID: 242dfda64e04
Revises: 55fa3bd704c1
Create Date: 2022-08-02 01:23:23.489592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '242dfda64e04'
down_revision = '55fa3bd704c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lastName', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('name', sa.String(length=50), nullable=False))
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('user', 'name')
    op.drop_column('user', 'lastName')
    # ### end Alembic commands ###
