"""empty message

Revision ID: 30f92496ecb7
Revises: fee891b28c55
Create Date: 2022-08-22 19:28:14.392533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30f92496ecb7'
down_revision = 'fee891b28c55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'emisor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comment', 'receptor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('user', sa.Column('received_comments_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'comment', ['received_comments_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'received_comments_id')
    op.alter_column('comment', 'receptor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comment', 'emisor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
