"""empty message

Revision ID: 4b1a60b5e2c1
Revises: f731487e976b
Create Date: 2022-09-12 15:10:49.039161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b1a60b5e2c1'
down_revision = 'f731487e976b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_owner_id_fkey', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['owner_id'], ['id'], ondelete='cascade')
    op.alter_column('profile', 'photo',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_constraint('profile_user_id_fkey', 'profile', type_='foreignkey')
    op.create_foreign_key(None, 'profile', 'user', ['user_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile', type_='foreignkey')
    op.create_foreign_key('profile_user_id_fkey', 'profile', 'user', ['user_id'], ['id'])
    op.alter_column('profile', 'photo',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_owner_id_fkey', 'post', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###
