"""empty message

Revision ID: 55fa3bd704c1
Revises: cc630ff0c562
Create Date: 2022-08-02 00:58:29.783672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55fa3bd704c1'
down_revision = 'cc630ff0c562'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.String(length=200), nullable=False))
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=60),
               existing_nullable=False)
    op.drop_constraint('user_phone_number_key', 'user', type_='unique')
    op.drop_column('user', 'date_of_birth')
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('phone_number', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('date_of_birth', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_phone_number_key', 'user', ['phone_number'])
    op.alter_column('user', 'username',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###
