"""empty message

Revision ID: f731487e976b
Revises: 30f92496ecb7
Create Date: 2022-09-07 22:04:26.487381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f731487e976b'
down_revision = '30f92496ecb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.drop_constraint('user_received_comments_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'received_comments_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('received_comments_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_received_comments_id_fkey', 'user', 'comment', ['received_comments_id'], ['id'])
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
