"""empty message

Revision ID: fee891b28c55
Revises: 3a797c7f9ef3
Create Date: 2022-08-22 19:16:00.690994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fee891b28c55'
down_revision = '3a797c7f9ef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_comments')
    op.add_column('comment', sa.Column('emisor_id', sa.Integer(), nullable=False))
    op.add_column('comment', sa.Column('receptor_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comment', 'user', ['emisor_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'user', ['receptor_id'], ['id'])
    op.alter_column('profile', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'receptor_id')
    op.drop_column('comment', 'emisor_id')
    op.create_table('users_comments',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], name='users_comments_comment_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='users_comments_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'comment_id', name='users_comments_pkey')
    )
    # ### end Alembic commands ###
